### ISSUE TITLE
Spanning Tree announcement interval may be too fast

### ISSUE THREAD

**Issue by devonh** [matrix-org/pinecone#10]
This comment is incorrect:
https://github.com/matrix-org/pinecone/blob/e692df1a5c427cd554a49c43a4c2a90f311041c4/router/tree.go#L31

The current value is this:
https://github.com/matrix-org/pinecone/blob/e692df1a5c427cd554a49c43a4c2a90f311041c4/router/peer.go#L32

I'm guessing that 15 minutes is the intended value.

The `PeerKeepaliveInterval` value, as is, is also being used for the peer connection read deadline. I tried it out in the simulator and these values definitely need to be coupled to prevent connection timeouts.

I don't think there would be any negative side effects to extending the spanning tree announcement interval since new peer's immediately obtain the current tree state already thanks to this bit:
https://github.com/matrix-org/pinecone/blob/e692df1a5c427cd554a49c43a4c2a90f311041c4/router/peer.go#L342-L345

**Comment by neilalexander** [comment]
Yes, I suspect it's just been left as the keepalive interval as the result of some debugging. We will be able to slow it down but will have to bump the protocol version to do so, so that we don't confuse older nodes. It hopefully won't affect the mobility performance negatively.

**Comment by neilalexander** [comment]
Ah, I remember what's going on here. The root announcements are being sent in place of the connection keepalives. There is still seemingly a bug somewhere where we don't respond well to dropping connections if we don't, so I need to investigate why that is.

**Comment by neilalexander** [comment]
This was fixed in the rewrite in 8b5be54cadc4fbef80513dff532821e6a946dab3 and is now 30 minutes. This might want revising in the future too but it's much better for now.
