### ISSUE TITLE
Nameing conflict with commercial product called PineCone made by Pine64

### ISSUE THREAD

**Issue by as365n4** [matrix-org/pinecone#16]
In Matrix Live S07E01 Matthew mentioned this repo, but you guys seem to have overlooked that there is a nameing conflict with a commercial product called PineCone which is made by Pine64. Links to Pine64 Wiki and Store for reference: [https://wiki.pine64.org/wiki/PineCone](url) [https://pine64.com/product/pinecone-bl602-evaluation-board/](url)

**Comment by neilalexander** [comment]
There will always be name conflicts in the world, especially when using standard English words, but we have no plans to change the project name.
