### ISSUE TITLE
Algorithm description: Spanning tree parent selection

### ISSUE THREAD

**Issue by hissssst** [matrix-org/pinecone#20]
# Overview

Hi, thank you for this awesome algorithm and this detailed description! During my attempt at writing an implementation of this algorithm  I came across small inconsistency in algorithm description (spanning tree part)

## Short description

When node receives a root-update it has already received (with the same public key and root sequence), but from another peer (after reparent timer), it runs parent selection algorithm. And this parent selection algorithm returns no suitable parent and the node switches it's state to root!

But I think that staying as a regular node without updating our parent is the right option!

And I think that iterating over the list of latest root announcements from all peers is not even necessary!

# Long description

Consider following topology where
```
  B
 /|
A |
 \|
  C
```
which means that every node has all other nodes as it peers

Let's assume that public keys are ordered the same way as the nodes are named (which means `A.public_key < B.public_key`)

And let's assume the C is root and A and B are regular nodes. C sends root update to A and B. A receives valid root update from parent with higher root sequence and stays in the same state with the same parent and sends this root update to B

Then two situations can happen:

1. B receives root update from A faster than it receives it from C:
In that case, B sets A as a parent, then it receives update from C it runs parent selection algorithm

2. B receives root update from C faster than it receives it from A:
In that case B sets C as a parent, and then when it receives update from A, it runs parent selection algorithm

## Let's run the parent selection!
> I'll run this for the first case, because for the second it is exactly the same, just switch C and A

### Legend:

`B` node already has these fields
* `B.root_public_key = C.public_key`
* `B.root_sequence = 1`

And `B` has received update from `A`, let's call it `update_from_a`
This update has fields
* `update_from_a.public_key = C.public_key`
* `update_from_a.root_sequence = 1`

And it was received at 12ms, let's store it inside update
* `update_from_a.received_at = 12ms`

And **now** `B` receives update from `C`, let's call it `update_from_c`
This update has fields 
* `update_from_c.public_key = C.public_key`
* `update_from_c.root_sequence = 1`

And it was received at 15ms (3ms later than update from `A`), let's store it inside update
* `update_from_c.received_at = 15ms`
---

### Running the algorithm

We start with the
```
best_public_key = C.public_key;
best_root_sequence = 1;
best_timestamp = 12;
best_candidate = empty
```

And we iterate peers `A` and `C`

Iteration over `A`
1. Does last root announcement received from this peer exceed the announcement timeout interval? **No**
2. Does the last root announcement received from this peer include our own public key in the Signing public key field of any of the signatures? **No**
3. Is the Root public key of the last peer update higher than the best key? **No**
4. Is the Root public key of the last peer update lower than the best key? **No**
5. Is the Root sequence of the last peer update higher than the best sequence? **No**
6. Is the Root sequence of the last peer update lower than the best sequence? **No**
7. Was the last peer update received before the best candidate? **No**

We stay with exactly the same `best` candidate as before

Iteration over `C`

1. Does last root announcement received from this peer exceed the announcement timeout interval? **No**
2. Does the last root announcement received from this peer include our own public key in the Signing public key field of any of the signatures? **No**
3. Is the Root public key of the last peer update higher than the best key? **No**
4. Is the Root public key of the last peer update lower than the best key? **No**
5. Is the Root sequence of the last peer update higher than the best sequence? **No**
6. Is the Root sequence of the last peer update lower than the best sequence? **No**
7. Was the last peer update received before the best candidate? **No**

So no best candidate was found, and we switch state to root (according to the docs)

---

# Suggestions and questions!

### Question about having no best candidate result in parent selection

Can you provide any situation where this is possible? 
I thought that this can happen when the node didn't receive any root update in last 45 minutes, but the parent selection is triggered when the node has just received the root update.

### Suggestion about iteration

Instead of iterating through all the peers, we can compare received root update to the root update we have just received from our parent:

* If we switch parent, we schedule sending root update to other peers (and unschedule all previously scheduled root updates)

* If we do not switch parent, we do nothing

**Comment by neilalexander** [comment]
> Running the algorithm
>
> We start with the
>
> ```
> best_public_key = C.public_key;
> ```

If we're talking about node B running the parent selection here, then it would start with `B.root_public_key` (== `C.public_key`) **if and only if** `B.root_public_key` is greater than or equal to our own key (`== B.public_key`).

If node `D` comes online, it is stronger than `C.public_key`, therefore:
* `D.public_key` is greater than `D.root_public_key` (which is currently `C.public_key`)
* `D.public_key` is greater than `A.root_public_key`, `B.root_public_key` and `C.root_public_key` (which is currently `C.public_key`)

> We start with the
> 
> ```
> best_timestamp = 12;
> ```

I think this is where the mistake lies in your implementation. You should start at `best_timestamp = MAX_UINT64`, not `best_timestamp = 12`. That way, when you reach this step:

> viii. If the last peer update was received before the best candidate, mark this peer as the best candidate instead.

... the existing parent would satisfy that condition and be chosen again as a potential parent candidate.

**Comment by hissssst** [comment]
> You should start at `best_timestamp = MAX_UINT64`

I think it would make sense to add this into algorithm documentation!

**Comment by neilalexander** [comment]
> I think it would make sense to add this into algorithm documentation!

How does this sound?

> vii. As a last resort tie-breaker, mark this peer as the best candidate and move onto the next if the peer's **Root public key** and **Root sequence** match the best key and best sequence, and either:
>  * This peer's update arrived before the update from the best candidate did, or;
>  * No other peer has been selected as the best candidate so far.

**Comment by hissssst** [comment]
Yeah, this sound great! Issue can be closed as soon as wiki gets updated

**Comment by neilalexander** [comment]
Great, the wiki has been updated. :-)
