### ISSUE TITLE
How well does pinecone scale?

### ISSUE THREAD

**Issue by lonnietc** [matrix-org/pinecone#41]
Hello,

If I understand correctly then Pinecone is similar to Yggdrasil which seems to scale pretty good from what I can see.

Does Pinecone scale well?

**Comment by 0x1a8510f2** [comment]
You might want to join [#p2p:matrix.org](https://matrix.to/#/!ZSWydcgXvkCqiTQynB:matrix.org?via=0x1a8510f2.space&via=systemausfall.ch&via=matrix.org); you're more likely to get a reply there sooner and also, it's a better place for questions than the issue tracker.

**Comment by lonnietc** [comment]
Thanks.  Will give it a try
